try {
    promiseReject('Mayday!');
} catch (err) {
    console.log(err); // Mayday!
}
  